name: maydon_app
description: The final project - Maydon application.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # icons
  cupertino_icons: ^1.0.2
  # splash screen
  flutter_native_splash: ^2.3.4
  bloc: ^8.1.2
  equatable: ^2.0.5
  firebase_auth: ^4.11.1
  firebase: ^9.0.3
  firebase_database: ^10.3.1
  firebase_core: ^2.20.0
  flutter_bloc: ^8.1.3
  firebase_crashlytics: ^3.4.2

flutter_native_splash:
  image: assets/icons/ic_facebook.png
  backgroundColor: 0xFFFFFFF


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Black.ttf
        - asset: assets/fonts/urbanist/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/urbanist/Urbanist-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/urbanist/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/urbanist/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/urbanist/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/urbanist/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/urbanist/Urbanist-Thin.ttf
          weight: 100



